[package]
name = "Prusce"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
local-ip-address = "0.6.5"
tokio = { version = "1.0", features = ["full"] }

[[bin]]
name = "test"
path = "src/test.rs"